### PR TITLE
#324 Scalable SVG

### PR DESCRIPTION
**Pull request by vbakke**
Ref: https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/issues/324 Page layout still needs fixing. But this fixes the SVG.

### CODE REVIEW

**Comment by vbakke** [comment]
Hang on. The mouseovers stopped working....

**Comment by vbakke** [comment]
Cannot replicate mouseover problems anymore. Not sure what happend. Will be interesting to hear what you experience. 

The chart still bounces around when I make screen narrow. I can have a look at that (but not right now), but that is technically not related to the SVG itself.

**Comment by vbakke** [comment]
This is just a comment to avoid marking the PR as stale

**Comment by wurstbrot** [comment]
@0x41head looks good?

**Comment by wurstbrot** [comment]
thank you for your PR

**Pull request merged**
