### PR TITLE
window title

### PR DESCRIPTION
**Pull request by piyushs131**
I have update the codebase and now the window titles is shown on DSOMM website. Kindly review it

### CODE REVIEW

**Comment by ptechofficial** [comment]
LGTM!
Appreciate the clean and direct code

**Review by ptechofficial — APPROVED** [review]

**Comment by 0x41head** [comment]
Unable to run a local copy of the code on my system.
@ptechofficial @wurstbrot can either of you confirm this issue ?
image

**Comment by wurstbrot** [comment]
I can confirm that the code is not running locally.

@piyushs131 Please fix code and code style
image


I am very sorry that I have added a fix to your PR.

**Comment by piyushs131** [comment]
ok Sir,
I will again check the codebase and try to fix the window title issue.

**Comment by wurstbrot** [comment]
please reopen with working code

**Comment by wurstbrot** [comment]
please also take a look at https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/issues/268#issuecomment-2006360461

**Comment by nishant2253** [comment]
> please also take a look at [#268 (comment)](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/issues/268#issuecomment-2006360461)

@wurstbrot  I have created a pull request, take a look at it #283

**Pull request closed without merging**
