### PR TITLE
Add in filter for team list filtering via a pipe

### PR DESCRIPTION
**Pull request by jdsmithit**
**Problem**
When you have a lot of teams ie 30+ and 7 plus groups the Ui becomes very clunky as the checkbox list is not filtered with the teams and groups.

**Change:**
A new enhancement to add in filtering the checkbox list, Also added a message when no teams are selected for a better user flow with this enhancement.

**Design Considerations**
Note: to stop this from breaking any functionality I have chosen to hide the check boxes and not remove items from the object.
Used a pipe to get the string value into the mat component checkbox and made it generic.

**Testing**
Preview and Testing below, 

Dsomm-new-feature-ezgif com-optimize

### CODE REVIEW

**Review by wurstbrot — APPROVED** [review]

**Comment by jdsmithit** [comment]
Ill move this to draft until i have manage to sort out the commit signing issue

**Comment by jdsmithit** [comment]
done

**Review by 0x41head — APPROVED** [review]
LGTM! Thank you for the change.

**Comment by wurstbrot** [comment]
Thank you, very cool :heart:

**Pull request merged**
