### PR TITLE
added activity level in excel

### PR DESCRIPTION
**Pull request by 0x41head**
for #321

### CODE REVIEW

**Review by wurstbrot — APPROVED** [review]

**Comment by 0x41head** [comment]
ready for merge

**Comment by wurstbrot** [comment]
thank you!

**Comment by Weltraumschaf** [comment]
LGTM

One question: For consistencies sake, should the level number be mapped to the [localized representation of the level](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/blob/469524c08904a0cea66d7c59ab2b83755a3e87cc/src/assets/YAML/meta.yaml#L34)?

**Comment by 101aryan** [comment]
@Weltraumschaf sounds fair.
@wurstbrot should we go ahead with it ?

**Comment by 0x41head** [comment]
@Weltraumschaf sounds fair
@wurstbrot should we go ahead with it ?

**Pull request merged**
