### PR TITLE
feat: add openCRE

### PR DESCRIPTION
**Pull request by wurstbrot**

### CODE REVIEW

**Comment by 101aryan** [comment]
@wurstbrot can you make the relevant changes to the yaml file, so that I can test it out locally ?

**Comment by 0x41head** [comment]
@wurstbrot can you make the relevant change in the YAML file, to test this change out locally ?

**Comment by wurstbrot** [comment]
Hi @0x41head it is in https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel-data/blob/main/src/assets/YAML/generated/generated.yaml

**Comment by 0x41head** [comment]
@wurstbrot the changes made do not break anything, but nothing is reflected on the frontend either. Is this the intended result ?

**Comment by wurstbrot** [comment]
> @wurstbrot the changes made do not break anything, but nothing is reflected on the frontend either. Is this the intended result ?

thank you for testing, I messed it up. Made it work here (incl. test)

**Comment by 0x41head** [comment]
LGTM :+1:

**Review by 0x41head — APPROVED** [review]
LGTM :+1:

**Pull request merged**
